/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_rtc_plugin_rawdata_MediaPreProcessing */

#ifndef _Included_io_agora_rtc_plugin_rawdata_MediaPreProcessing
#define _Included_io_agora_rtc_plugin_rawdata_MediaPreProcessing
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL
Java_io_agora_rtc_hechang_jni_MediaPreProcessing_startAudioCustom(JNIEnv *env, jclass type,
                                                                jboolean isCustomRecord,
                                                                jboolean isCustomPlay);

JNIEXPORT void JNICALL
Java_io_agora_rtc_hechang_jni_MediaPreProcessing_stopAndrelease(JNIEnv *env, jclass type);

#ifdef __cplusplus
}
#endif
#endif